import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Navigation from "../components/Navigation";
import Search from "../components/Search";
import Selector from "../components/Selector";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div
          className=" flex justify-between flex-col gap-24 desktop:gap-0
            desktop:flex-row desktop:py-32  desktop:justify-start"
        >
          <div className="desktop:pl-32">
            <Navigation />
          </div>
          <div className="flex flex-col gap-56 px-16 desktop:px-32 desktop:pt-24 ">
            <div className="flex justify-between gap-24">
              <Search />
              <Selector />
            </div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
