import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Navigation from "../components/Navigation";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div
          className=" flex justify-between flex-col gap-24 desktop:gap-0
            desktop:flex-row desktop:py-32  desktop:justify-start items-center desktop:items-start"
        >
          <div className="desktop:pl-32">
            <Navigation />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
